public class Demo5Class {
    public static string helloMessage() {
    return('This is demo 5"');
    
    }
    public static string helloMessage1() {
        return('second pass"');}
		
	 public static string feature1() {
        return('feature 1 added"');}
    
   public static string feature2() {
        return('feature 2 added"');}
		
		 
   public static string deploy() {
        return('the code is deploying"');}
}