public class O_O_P {
public  O_O_P() {
System.debug('There are 4 main pillars of Oops');
}
    
    public static void inheritance() {
        System.debug('There are five types');
    }
    
    public static void abstraction() {
    System.debug('There are two way to achieve abstraction');
    System.debug('Abstract class and Interface');
}

public static void encapsulation() {
    System.debug('Wrap a data in single unit and use all variable as a private and use getter and setter method as a public');
}

public static void polymorphism() {
    System.debug('perform one task in multipe way, we use method overloading and overriding to obtain polymorphism');
    }
    
    public static void nothing() {
    System.debug('there is nothing');
    }
    
    public static void fully() {
    System.debug('java is not a fully object oriented programing');
    }
    public static void multi_inheritance() {
    System.debug('java does not support multi_inheritance');
    }
    public static void why_java_is_partial_oops() {
    System.debug('due to primitive data type');
    }
    
}