public class OOPS {
    
    public static void inheritance() {
        System.debug('There are five types');
    }
    
    public static void abstraction() {
    System.debug('There are two way to achieve abstraction');
    System.debug('Abstract class and Interface');
}

public static void encapsulation() {
    System.debug('Wrap a data in single unit and use all variable as a private and use getter and setter method as a public');
}

public static void polymorphism() {
    System.debug('perform one task in multipe way, we use method overloading and overriding to obtain polymorphism');
    }
    
    
  
}